version: '3.8'

services:
  app:
    image: evershop/evershop:latest
    restart: always
    environment:
      DB_HOST: evershop-demo_database
      DB_PORT: 5432
      DB_PASSWORD: 1751282a12b428ab48cb
      DB_USER: postgres
      DB_NAME: evershop-demo
    networks:
      - myevershop
    depends_on:
      - database
    ports:
      - 3000:3000

networks:
  myevershop:
    name: MyEverShop
    driver: bridge

volumes:
  postgres-data:
